angular.module('edgefolio.constants.LegalStructures', [])
.constant('LegalStructures', {
  "01": "Partnership (3C1)",
  "02": "Partnership (3C7)",
  "03": "Corporation",
  "04": "Limited Liability Company",
  "05": "Closed Ended Investment Company",
  "06": "Exempted Limited Partnership",
  "08": "Open Ended Investment Company",
  "09": "SICAV",
  "11": "Non-Exempted Limited Partnership",
  "12": "Registered Hedge Fund",
  "20": "SeparateAccount",
  "22": "Unit Trust",
  "23": "FCP",
  "24": "SICAF",
  "25": "Trust Units",
  "26": "Investment Trust",
  "27": "Unit Investment Trust",
  "28": "Grantor Trust",
  "29": "Trusts",
  "30": "Pooled",
  "31": "Custom Fund",
  "32": "Market Index",
  "33": "Managed Account",
  "34": "Unstructured Hedge Fund",
  "35": "FCIMT",
  "36": "FIP",
  "37": "FCPI",
  "38": "FCPE",
  "39": "SIMCAV",
  "40": "Structured Product",
  "41": "Property Syndicate",
  "42": "IGSA",
  "43": "CIT",
  "45": "Unlisted Closed End Investment Company",
  "50": "Limited Liability Partnership"
});
